spring.application.name=Netdisk
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/netdisk?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
spring.datasource.username=root
spring.datasource.password=19623333my
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.configuration.map-underscore-to-camel-case=true

netdisk.upload.base-dir=uploads/
netdisk.upload.url-prefix=/files/
netdisk.upload.avatar-subdir=avatar
netdisk.upload.file-subdir=files

spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
